### ISSUE TITLE
flow_from_dataframe breaks if index does not contain "0" label

### ISSUE THREAD

**Issue by peter-schmidbauer** [keras-team/keras-preprocessing#151]
ImageDataGenerator.flow_from_dataframe() breaks if the provided DataFrame does not contain a numeric Index containing the number 0. This presumably happens due to an attempt to access the first column using df.loc instead of df.iloc in keras_preprocessing\image.py.

```python
>>> import pandas as pd
>>> from keras.preprocessing.image import ImageDataGenerator
Using TensorFlow backend.
>>> df = pd.DataFrame({"filename": ["test1.png", "test2.png"], "class": ["foo", "bar"]}, index=[1, 2])
>>> gen = ImageDataGenerator()
>>> gen.flow_from_dataframe(df, "data/train")
Traceback (most recent call last):
  File "...\lib\site-packages\pandas\core\indexing.py", line 1506, in _has_valid_type
    error()
  File "...\lib\site-packages\pandas\core\indexing.py", line 1501, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [0] is not in the [index]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\keras_preprocessing\image.py", line 1107, in flow_from_dataframe
    interpolation=interpolation)
  File "...\lib\site-packages\keras_preprocessing\image.py", line 2099, in __init__
    if self.df.loc[0, x_col].endswith("." + ext):
  File "...\lib\site-packages\pandas\core\indexing.py", line 1367, in __getitem__
    return self._getitem_tuple(key)
  File "...\lib\site-packages\pandas\core\indexing.py", line 858, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "...\lib\site-packages\pandas\core\indexing.py", line 991, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "...\lib\site-packages\pandas\core\indexing.py", line 1626, in _getitem_axis
    self._has_valid_type(key, axis)
  File "...\lib\site-packages\pandas\core\indexing.py", line 1514, in _has_valid_type
    error()
  File "...\lib\site-packages\pandas\core\indexing.py", line 1501, in error
    axis=self.obj._get_axis_name(axis)))
KeyError: 'the label [0] is not in the [index]'

```

**Comment by Vijayabhaskar96** [comment]
This issue was already fixed. Keras has the older version of `keras_preprocessing` , Update your Keras_preprocessing library to the latest Github version and use it by importing it directly from `keras_preprocessing`, not from `keras.preprocessing`.
