### ISSUE TITLE
ImageDataGenerator: Mismatch between image and mask # samples with workers > 1

### ISSUE THREAD

**Issue by Zahlii** [keras-team/keras-preprocessing#234]
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ x] Check that you are up-to-date with the master branch of keras-preprocessing. You can update with:
`pip install git+git://github.com/keras-team/keras-preprocessing.git --upgrade --no-deps`

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

        import numpy as np
        from keras.preprocessing.image import ImageDataGenerator
        from keras.layers import Conv2D
        from keras import Sequential
    
        x = np.random.random((250, 128, 128, 3))
        y = x ** 2
    
        kw = dict(width_shift_range=5,
                  height_shift_range=5,
                  rotation_range=15,
                  shear_range=5,
                  zoom_range=0.1,
                  vertical_flip=True)
        augment_x_ = ImageDataGenerator(**kw)
        augment_y_ = augment_x_.__class__(**kw)
    
        seed = np.random.randint(0, 2 ** 32 - 1)
    
        augment_x_.fit(x, seed=seed, augment=False)
        augment_y_.fit(x, seed=seed, augment=False)
    
        batch_size = 16
    
        gen_x = augment_x_.flow(x, batch_size=batch_size, seed=seed)
        gen_y = augment_y_.flow(y, batch_size=batch_size, seed=seed)
        train_gen = zip(gen_x, gen_y)
    
    
        s = Sequential()
        s.add(Conv2D(3, (3, 3), input_shape=(128, 128, 3), padding="same"))
        s.compile(loss="mse", optimizer="Adam")
        s.fit_generator(train_gen, workers=8, steps_per_epoch=250 // 16, epochs=4)
    
        """
        Traceback (most recent call last):
          File ".../PycharmProjects/bla.py", line 33, in <module>
            s.fit_generator(train_gen, workers=8, steps_per_epoch=250 // 16, epochs=4)
          File "/usr/local/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
            return func(*args, **kwargs)
          File "/usr/local/lib/python3.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
            initial_epoch=initial_epoch)
          File "/usr/local/lib/python3.7/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
            class_weight=class_weight)
          File "/usr/local/lib/python3.7/site-packages/keras/engine/training.py", line 1211, in train_on_batch
            class_weight=class_weight)
          File "/usr/local/lib/python3.7/site-packages/keras/engine/training.py", line 804, in _standardize_user_data
            check_array_length_consistency(x, y, sample_weights)
          File "/usr/local/lib/python3.7/site-packages/keras/engine/training_utils.py", line 237, in check_array_length_consistency
            'and ' + str(list(set_y)[0]) + ' target samples.')
        ValueError: Input arrays should have the same number of samples as target arrays. Found 10 input samples and 16 target samples.
        """

This is the case for all workers > 1. It does not change if I change the steps_per_epoch. It does not help if I change the batch size.

**Comment by Zahlii** [comment]
If I change the batch_size to be a divider of the data size, it works, i.e. making sure that total_sample_data % batch_size = 0. However, I don't think this is a viable solution.
