### ISSUE TITLE
Unable to train with RGBA images; RGB work fine

### ISSUE THREAD

**Issue by Benz-Tracxpoint** [keras-team/keras-preprocessing#63]
I have training data that are RGBA images stored as png files. When I read them in as RGB images using flow_from_directory everything runs smoothly.

But if I set the 'color_mode' argument of flow_from_directory to 'rgba', as in he documentation, I get the following error when trying to run fit_generator:
```
`Epoch 1/120
Traceback (most recent call last):
  File "training_keras.py", line 326, in <module>
    train_model(MODEL_NAME,BASE_DIR,OUTPUT_DIR,GPUS,NUM_EPOCHS,BATCH_SIZE,WIDTH,HEIGHT,MODEL_TYPE,WORKERS,DATA_FRACTION,TRAIN_ALL,FIRST_LAYER,FCN_SIZE,VALIDATION_DIR)
  File "training_keras.py", line 314, in train_model
    model.fit_generator( train_generator,steps_per_epoch=(train_generator.n/(BATCH_SIZE)/DATA_FRACTION),epochs=NUM_EPOCHS,callbacks=cbks,workers=WORKERS, validation_data=validate_generator)
  File "/usr/local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/usr/local/lib/python3.6/site-packages/keras_preprocessing/image.py", line 1441, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/usr/local/lib/python3.6/site-packages/keras_preprocessing/image.py", line 1932, in _get_batches_of_transformed_samples
    batch_x[i] = x
ValueError: could not broadcast input array from shape (296,296,3) into shape (296,296,4)
`
```
Why does this happen?

Thanks!

P.S.
Keras is version 2.2.4
Keras-Preprocessing is version 1.0.6
Tensorflow-GPU is version 1.10.1

**Comment by Dref360** [comment]
Hi,
We could work on this better if you could provide a standalone reproducible example.
Some advices:
* Don't use custom data or custom paths.
* Use random arrays or even np.ones, np.zeros.
* The example should run with Keras (and deps) alone.
* Should be Python3 compatible.
* Should not be OS specific.
* The file should reproduce the bug with **high* fidelity.
* Link to a gist would be appreciated.

Thanks!
Dref360

**Comment by rragundez** [comment]
It seems to work.
```
import numpy as np
import scipy.misc
import pandas as pd
import random
from keras_preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import os

pixel_val = 1
filenames = []
for i in range(20):
    directory = '/tmp/class_{}'.format(i % 2)
    os.makedirs(directory, exist_ok=True)
    filename = directory +'/{}.png'.format(i)   
    plt.imsave(filename, np.random.uniform(0, 1, size=(3, 3, 4)), format='png')
        

generator = ImageDataGenerator().flow_from_directory(
    '/tmp',
    color_mode='rgba',
    batch_size=3,
    target_size=(3, 3),
    classes=['class_0', 'class_1'],
)
next(generator)
```
